### ISSUE TITLE
not able to download the show-and-tell-2M.zip 

### ISSUE THREAD

**Issue by CETAKHILVB** [ColeMurray/medium-show-and-tell-caption-generator#6] opened 2019-04-02 20:32 UTC
Hi,
Thanks for this wonderful post explaining the code working and split-up.
:)
But am facing an issue, not able to download the show-and-tell-2M.zip file, dont know why, here is the error I am getting!
“Downloading model to /opt/app/etc/show-and-tell-2M.zip
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): drive.google.com
DEBUG:urllib3.connectionpool:https://drive.google.com:443 “GET /uc?export=download&id=15Juh0gaYR0qv8GjRL1EvsigErdQXTmnt HTTP/1.1” 200 None
Traceback (most recent call last):
 File “/opt/app/bin/download_model.py”, line 66, in <module>
 download_and_extract_model(‘show-and-tell-2M’, args.model_dir)
 File “/opt/app/bin/download_model.py”, line 22, in download_and_extract_model
 with zipfile.ZipFile(destination, ‘r’) as zip_ref:
 File “/usr/lib/python3.5/zipfile.py”, line 1026, in __init__
 self._RealGetContents()
 File “/usr/lib/python3.5/zipfile.py”, line 1093, in _RealGetContents
 raise BadZipFile(“File is not a zip file”)
zipfile.BadZipFile: File is not a zip file”

Any idea why this error? How to fix this?

Thanks in advance!

**Comment by ColeMurray** [comment] 2019-04-03 04:17
Hello @CETAKHILVB,

Can you paste the command you used to run this?

I ran the command provided below and was able to succesfully download.

```
sudo docker run -e PYTHONPATH=$PYTHONPATH:/opt/app -v $PWD:/opt/app \
-it colemurray/medium-show-and-tell-caption-generator \
python3 /opt/app/bin/download_model.py \
--model-dir /opt/app/etc
Password:
Downloading model to /opt/app/etc/show-and-tell-2M.zip
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): drive.google.com
DEBUG:urllib3.connectionpool:https://drive.google.com:443 "GET /uc?export=download&id=15Juh0gaYR0qv8GjRL1EvsigErdQXTmnt HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): drive.google.com
DEBUG:urllib3.connectionpool:https://drive.google.com:443 "GET /uc?export=download&confirm=XasJ&id=15Juh0gaYR0qv8GjRL1EvsigErdQXTmnt HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): doc-0g-8g-docs.googleusercontent.com
DEBUG:urllib3.connectionpool:https://doc-0g-8g-docs.googleusercontent.com:443 "GET /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/8cs89pgn7ef1dpcp96thernemi4m7hgs/1554264000000/00759866066582678587/*/15Juh0gaYR0qv8GjRL1EvsigErdQXTmnt?e=download HTTP/1.1" 200 None
Extracting model to /opt/app/etc
➜  medium-show-and-tell-caption-generator git:(master) ✗ ls etc/
show-and-tell-2M.zip show-and-tell.pb
```

**Comment by CETAKHILVB** [comment] 2019-04-03 17:29
Hai @ColeMurray ,

Thanks for the reply.
I am using the same command as you have used.
"sudo docker run -e PYTHONPATH=$PYTHONPATH:/opt/app -v $PWD:/opt/app -it colemurray/medium-show-and-tell-caption-generator python3 /opt/app/bin/download_model.py --model-dir /opt/app/etc
Downloading model to /opt/app/etc/show-and-tell-2M.zip
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): drive.google.com
DEBUG:urllib3.connectionpool:https://drive.google.com:443 "GET /uc?export=download&id=15Juh0gaYR0qv8GjRL1EvsigErdQXTmnt HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/opt/app/bin/download_model.py", line 66, in <module>
    download_and_extract_model('show-and-tell-2M', args.model_dir)
  File "/opt/app/bin/download_model.py", line 22, in download_and_extract_model
    with zipfile.ZipFile(destination, 'r') as zip_ref:
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
![show and tell error](https://user-images.githubusercontent.com/23625799/55499590-fd201500-5663-11e9-9e68-3873cf7d19a1.png)
![show and tell error](https://user-images.githubusercontent.com/23625799/55499609-0a3d0400-5664-11e9-804a-e2655891a46e.png)

"

**Comment by CETAKHILVB** [comment] 2019-04-03 17:37
Is there any other way I can download the zip file?

**Comment by ColeMurray** [comment] 2019-07-03 06:28
@CETAKHILVB Closing this as I was unable to reproduce. If you are still experiencing issues, reopen and I can find an alternate way to transfer the model.

**Closed as completed by ColeMurray** 2019-07-03 06:28 UTC
